### PR TITLE
Feature/alert avatar button

### PR DESCRIPTION
**Pull request by govindappaarun**
- added alert component and its preview page
- added avatar component and its preview
- added button component with its preview

### CODE REVIEW

**Review by BalajiHarinath — APPROVED** [review]
Could you please place the avatars in ascending order. I meant the second one is smaller than the first one. Other than that everything looks good to me

**Review by vrx29 — APPROVED** [review]
Nice work. Your code is clean.

**Review by VLeads — APPROVED** [review]
Code looks clean !!

**Comment by yash9263** [comment]
Looks good to me

**Pull request merged**
