### PR TITLE
Feature/component documentation

### PR DESCRIPTION
**Pull request by govindappaarun**
- add documentation site, and style
 -  write document, for now its lorem ( will add writing later )
 - refactor navigation

### CODE REVIEW

**Comment by Vishnu-Aithal** [comment]
Looks good!
Some small suggestions - 
-list head in aside requires some margin left
-logout text in navbar requires color change for contrast
-some padding for stars
-felt default buttons are too big, maybe a btn-small variation with smaller padding and line height

**Review by Developers-codz — APPROVED** [review]
code and UI both looks good to me. Just a suggestion you can give some padding in text utility which has colored background

**Comment by Vishnu-Aithal** [comment]
Looks Good !
some small findings -

image
-Something is blocking bottom part of aside section when you scroll

-navbar can add align items center to center header

**Review by yash9263 — APPROVED** [review]

**Comment by yash9263** [comment]
Everything looks good to me can follow up comments made above

**Review by BISINIGISHIVANI — COMMENTED** [review]
give cursor pointer to rating ,nav so that user can know those are clickble .

**Pull request merged**
